name: dmtransport
description: Connects drivers to DM Transport admin.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.11+15

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  document_scanner:
    git:
      url: https://github.com/shivang51/document_scanner.git
      ref: ec3ec48
  file_picker: ^5.3.4
  firebase_analytics: ^10.4.5
  firebase_app_check: ^0.2.1+8
  firebase_core: ^2.15.1
  firebase_database: ^10.2.6
  firebase_messaging: ^14.6.8
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.0.2
  in_app_notification: ^1.1.2
  intl_phone_number_input: ^0.7.3+1
  package_info_plus: ^4.1.0
  path: any
  path_provider: ^2.1.0
  pdf: ^3.10.4
  provider: ^6.0.5
  screenshot: ^2.1.0
  shared_preferences: ^2.2.3
  syncfusion_flutter_pdfviewer: ^22.2.12
  table_calendar: ^3.0.9
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  camera: ^0.11.0+1
  permission_handler: ^11.3.0
  flutter_image_filters: ^0.0.17
  image_cropper: ^1.5.1
  google_fonts: ^6.2.0
  printing: ^5.12.0
  # intl: ^0.17.0


dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
